TYPE1:
  backwardAccelerationSpeed: 0.1
  keyName: 레이싱카
  carType: TYPE3
  deceleration: 0.2
  forwardAccelerationSpeed: 0.1
  gravity: 0.7
  maxBackwardSpeed: -0.2
  maxForwardSpeed: 0.5
  nowForwardSpeed: 0.0
  seatCount: 4
  small: true
  turningAcceleration: 7.0
TYPE2:
  backwardAccelerationSpeed: 0.1
  keyName: 레이싱카2
  carType: TYPE6
  deceleration: 0.2
  forwardAccelerationSpeed: 0.1
  gravity: 0.7
  maxBackwardSpeed: -0.2
  maxForwardSpeed: 0.5
  nowForwardSpeed: 0.0
  seatCount: 4
  small: true
  turningAcceleration: 7.0
TYPE3:
  backwardAccelerationSpeed: 0.1
  carType: TYPE9
  deceleration: 0.2
  forwardAccelerationSpeed: 0.1
  gravity: 0.7
  maxBackwardSpeed: -0.2
  maxForwardSpeed: 0.5
  nowForwardSpeed: 0.0
  seatCount: 4
  small: true
  turningAcceleration: 7.0
TYPE4:
  backwardAccelerationSpeed: 0.1
  carType: TYPE12
  deceleration: 0.2
  forwardAccelerationSpeed: 0.1
  gravity: 0.7
  maxBackwardSpeed: -0.2
  maxForwardSpeed: 0.5
  nowForwardSpeed: 0.0
  seatCount: 4
  small: true
  turningAcceleration: 7.0
TYPE5:
  backwardAccelerationSpeed: 0.1
  carType: TYPE16
  deceleration: 0.2
  forwardAccelerationSpeed: 0.1
  gravity: 0.7
  maxBackwardSpeed: -0.2
  maxForwardSpeed: 0.5
  nowForwardSpeed: 0.0
  seatCount: 2
  small: true
  turningAcceleration: 7.0
TYPE6:
  backwardAccelerationSpeed: 0.1
  carType: TYPE19
  deceleration: 0.2
  forwardAccelerationSpeed: 0.1
  gravity: 0.7
  maxBackwardSpeed: -0.2
  maxForwardSpeed: 0.5
  nowForwardSpeed: 0.0
  seatCount: 2
  small: true
  turningAcceleration: 7.0
TYPE7:
  backwardAccelerationSpeed: 0.1
  carType: TYPE22
  deceleration: 0.2
  forwardAccelerationSpeed: 0.1
  gravity: 0.7
  maxBackwardSpeed: -0.2
  maxForwardSpeed: 0.5
  nowForwardSpeed: 0.0
  seatCount: 2
  small: true
  turningAcceleration: 7.0
TYPE8:
  backwardAccelerationSpeed: 0.1
  carType: TYPE25
  deceleration: 0.2
  forwardAccelerationSpeed: 0.1
  gravity: 0.7
  maxBackwardSpeed: -0.2
  maxForwardSpeed: 0.5
  nowForwardSpeed: 0.0
  seatCount: 4
  small: true
  turningAcceleration: 7.0
TYPE9:
  backwardAccelerationSpeed: 0.1
  carType: TYPE28
  deceleration: 0.2
  forwardAccelerationSpeed: 0.1
  gravity: 0.7
  maxBackwardSpeed: -0.2
  maxForwardSpeed: 0.5
  nowForwardSpeed: 0.0
  seatCount: 4
  small: true
  turningAcceleration: 7.0
TYPE10:
  backwardAccelerationSpeed: 0.1
  carType: TYPE32
  deceleration: 0.2
  forwardAccelerationSpeed: 0.1
  gravity: 0.7
  maxBackwardSpeed: -0.2
  maxForwardSpeed: 0.5
  nowForwardSpeed: 0.0
  seatCount: 4
  small: true
  turningAcceleration: 7.0
TYPE11:
  backwardAccelerationSpeed: 0.1
  carType: TYPE35
  deceleration: 0.2
  forwardAccelerationSpeed: 0.1
  gravity: 0.7
  maxBackwardSpeed: -0.2
  maxForwardSpeed: 0.5
  nowForwardSpeed: 0.0
  seatCount: 2
  small: true
  turningAcceleration: 7.0
TYPE12:
  backwardAccelerationSpeed: 0.1
  carType: TYPE38
  deceleration: 0.2
  forwardAccelerationSpeed: 0.1
  gravity: 0.7
  maxBackwardSpeed: -0.2
  maxForwardSpeed: 0.5
  nowForwardSpeed: 0.0
  seatCount: 4
  small: true
  turningAcceleration: 7.0
TYPE13:
  backwardAccelerationSpeed: 0.1
  carType: TYPE41
  deceleration: 0.2
  forwardAccelerationSpeed: 0.1
  gravity: 0.7
  maxBackwardSpeed: -0.2
  maxForwardSpeed: 0.5
  nowForwardSpeed: 0.0
  seatCount: 4
  small: true
  turningAcceleration: 7.0
TYPE14:
  backwardAccelerationSpeed: 0.1
  carType: TYPE44
  deceleration: 0.2
  forwardAccelerationSpeed: 0.1
  gravity: 0.7
  maxBackwardSpeed: -0.2
  maxForwardSpeed: 0.5
  nowForwardSpeed: 0.0
  seatCount: 4
  small: true
  turningAcceleration: 7.0
TYPE15:
  backwardAccelerationSpeed: 0.1
  carType: TYPE48
  deceleration: 0.2
  forwardAccelerationSpeed: 0.1
  gravity: 0.7
  maxBackwardSpeed: -0.2
  maxForwardSpeed: 0.5
  nowForwardSpeed: 0.0
  seatCount: 4
  small: true
  turningAcceleration: 7.0
TYPE16:
  backwardAccelerationSpeed: 0.1
  carType: TYPE51
  deceleration: 0.2
  forwardAccelerationSpeed: 0.1
  gravity: 0.7
  maxBackwardSpeed: -0.2
  maxForwardSpeed: 0.5
  nowForwardSpeed: 0.0
  seatCount: 4
  small: true
  turningAcceleration: 7.0
TYPE17:
  backwardAccelerationSpeed: 0.1
  carType: TYPE54
  deceleration: 0.2
  forwardAccelerationSpeed: 0.1
  gravity: 0.7
  maxBackwardSpeed: -0.2
  maxForwardSpeed: 0.5
  nowForwardSpeed: 0.0
  seatCount: 4
  small: true
  turningAcceleration: 7.0
TYPE18:
  backwardAccelerationSpeed: 0.1
  carType: TYPE57
  deceleration: 0.2
  forwardAccelerationSpeed: 0.1
  gravity: 0.7
  maxBackwardSpeed: -0.2
  maxForwardSpeed: 0.5
  nowForwardSpeed: 0.0
  seatCount: 4
  small: true
  turningAcceleration: 7.0
TYPE19:
  backwardAccelerationSpeed: 0.1
  carType: TYPE60
  deceleration: 0.2
  forwardAccelerationSpeed: 0.1
  gravity: 0.7
  maxBackwardSpeed: -0.2
  maxForwardSpeed: 0.5
  nowForwardSpeed: 0.0
  seatCount: 4
  small: true
  turningAcceleration: 7.0
TYPE20:
  backwardAccelerationSpeed: 0.1
  carType: TYPE64
  deceleration: 0.2
  forwardAccelerationSpeed: 0.1
  gravity: 0.7
  maxBackwardSpeed: -0.2
  maxForwardSpeed: 0.5
  nowForwardSpeed: 0.0
  seatCount: 4
  small: true
  turningAcceleration: 7.0
TypeList:
  - TYPE1
  - TYPE2
  - TYPE3
  - TYPE4
  - TYPE5
  - TYPE6
  - TYPE7
  - TYPE8
  - TYPE9
  - TYPE10
  - TYPE11
  - TYPE12
  - TYPE13
  - TYPE14
  - TYPE15
  - TYPE16
  - TYPE17
  - TYPE18
  - TYPE19
  - TYPE20
CoolDown: 5
