TYPE1:
  backwardAccelerationSpeed: 0.1
  carType: TYPE1
  deceleration: 0.2
  forwardAccelerationSpeed: 0.1
  gravity: 0.7
  maxBackwardSpeed: -0.2
  maxForwardSpeed: 0.5
  nowForwardSpeed: 0.0
  seatCount: 4
  small: false
  turningAcceleration: 7.0
TYPE2:
  backwardAccelerationSpeed: 0.1
  carType: TYPE2
  deceleration: 0.2
  forwardAccelerationSpeed: 0.1
  gravity: 0.7
  maxBackwardSpeed: -0.2
  maxForwardSpeed: 0.5
  nowForwardSpeed: 0.0
  seatCount: 4
  small: false
  turningAcceleration: 7.0
TYPE3:
  backwardAccelerationSpeed: 0.1
  carType: TYPE3
  deceleration: 0.2
  forwardAccelerationSpeed: 0.1
  gravity: 0.7
  maxBackwardSpeed: -0.2
  maxForwardSpeed: 0.5
  nowForwardSpeed: 0.0
  seatCount: 4
  small: false
  turningAcceleration: 7.0
TYPE4:
  backwardAccelerationSpeed: 0.1
  carType: TYPE4
  deceleration: 0.2
  forwardAccelerationSpeed: 0.1
  gravity: 0.7
  maxBackwardSpeed: -0.2
  maxForwardSpeed: 0.5
  nowForwardSpeed: 0.0
  seatCount: 4
  small: false
  turningAcceleration: 7.0
TYPE5:
  backwardAccelerationSpeed: 0.1
  carType: TYPE5
  deceleration: 0.2
  forwardAccelerationSpeed: 0.1
  gravity: 0.7
  maxBackwardSpeed: -0.2
  maxForwardSpeed: 0.5
  nowForwardSpeed: 0.0
  seatCount: 2
  small: true
  turningAcceleration: 7.0
TYPE6:
  backwardAccelerationSpeed: 0.1
  carType: TYPE6
  deceleration: 0.2
  forwardAccelerationSpeed: 0.1
  gravity: 0.7
  maxBackwardSpeed: -0.2
  maxForwardSpeed: 0.5
  nowForwardSpeed: 0.0
  seatCount: 2
  small: true
  turningAcceleration: 7.0
TYPE7:
  backwardAccelerationSpeed: 0.1
  carType: TYPE7
  deceleration: 0.2
  forwardAccelerationSpeed: 0.1
  gravity: 0.7
  maxBackwardSpeed: -0.2
  maxForwardSpeed: 0.5
  nowForwardSpeed: 0.0
  seatCount: 2
  small: true
  turningAcceleration: 7.0
TYPE8:
  backwardAccelerationSpeed: 0.1
  carType: TYPE8
  deceleration: 0.2
  forwardAccelerationSpeed: 0.1
  gravity: 0.7
  maxBackwardSpeed: -0.2
  maxForwardSpeed: 0.5
  nowForwardSpeed: 0.0
  seatCount: 4
  small: false
  turningAcceleration: 7.0
TYPE9:
  backwardAccelerationSpeed: 0.1
  carType: TYPE9
  deceleration: 0.2
  forwardAccelerationSpeed: 0.1
  gravity: 0.7
  maxBackwardSpeed: -0.2
  maxForwardSpeed: 0.5
  nowForwardSpeed: 0.0
  seatCount: 4
  small: false
  turningAcceleration: 7.0
TYPE10:
  backwardAccelerationSpeed: 0.1
  carType: TYPE10
  deceleration: 0.2
  forwardAccelerationSpeed: 0.1
  gravity: 0.7
  maxBackwardSpeed: -0.2
  maxForwardSpeed: 0.5
  nowForwardSpeed: 0.0
  seatCount: 4
  small: false
  turningAcceleration: 7.0
TYPE11:
  backwardAccelerationSpeed: 0.1
  carType: TYPE11
  deceleration: 0.2
  forwardAccelerationSpeed: 0.1
  gravity: 0.7
  maxBackwardSpeed: -0.2
  maxForwardSpeed: 0.5
  nowForwardSpeed: 0.0
  seatCount: 2
  small: true
  turningAcceleration: 7.0
TYPE12:
  backwardAccelerationSpeed: 0.1
  carType: TYPE12
  deceleration: 0.2
  forwardAccelerationSpeed: 0.1
  gravity: 0.7
  maxBackwardSpeed: -0.2
  maxForwardSpeed: 0.5
  nowForwardSpeed: 0.0
  seatCount: 4
  small: false
  turningAcceleration: 7.0
TypeList:
  - TYPE1
  - TYPE2
  - TYPE3
  - TYPE4
  - TYPE5
  - TYPE6
  - TYPE7
  - TYPE8
  - TYPE9
  - TYPE10
  - TYPE11
  - TYPE12
CoolDown: 5
